USE portaltech;

DROP TABLE IF EXISTS FELHASZNALO;

CREATE TABLE FELHASZNALO(
  f_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  f_nev VARCHAR(200) NOT NULL UNIQUE,
  jelszo VARCHAR(200) NOT NULL,
  nev VARCHAR(200) NOT NULL,
  admin BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS TERMEK;

CREATE TABLE TERMEK(
  t_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nev VARCHAR(200) NOT NULL,
  leiras VARCHAR(2048),
  ar INT NOT NULL
);

DROP TABLE IF EXISTS KOSAR;

CREATE TABLE KOSAR(
  t_id INT NOT NULL,
  f_id INT NOT NULL,
  darab INT NOT NULL,
  fizetve BOOLEAN NOT NULL,
  CONSTRAINT pk_kosar PRIMARY KEY (t_id, f_id)
)